export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PROFILE_FEATCHED = 'PROFILE_FEATCHED';

export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const DOCTORS_SPECIALITIES = 'DOCTORS_SPECIALITIES'
export const GET_DOCTORS = 'GET_DOCTORS'
export const FILTER_C = 'FILTER_C'

export const GET_PATIENTS = 'GET_PATIENTS'

export const TOGGLE_APPOINT = 'TOGGLE_APPOINT'
export const MY_APPOINTMENTS = 'MY_APPOINTMENTS'